/* eslint-env node */
// server/email/sendComplaintEmail.js
//
// Very small helper that sends a complaint report to the store owner.
// In production this can fan out to multiple managers or Slack, etc.

const nodemailer = require("nodemailer");

const {
  EMAIL_SMTP_HOST,
  EMAIL_SMTP_PORT,
  EMAIL_SMTP_USER,
  EMAIL_SMTP_PASS,
  COMPLAINTS_TO,
} = process.env;

if (!EMAIL_SMTP_USER || !EMAIL_SMTP_PASS) {
  console.warn("[email] Missing SMTP credentials — complaint emails disabled.");
}

async function sendComplaintEmail(payload) {
  if (!EMAIL_SMTP_USER || !EMAIL_SMTP_PASS) {
    console.warn("[email] Complaints email skipped (SMTP disabled).");
    return;
  }

  const transporter = nodemailer.createTransport({
    host: EMAIL_SMTP_HOST,
    port: Number(EMAIL_SMTP_PORT) || 587,
    auth: {
      user: EMAIL_SMTP_USER,
      pass: EMAIL_SMTP_PASS,
    },
  });

  const {
    phone,
    issue,
    orderDateHint,
    locationId,
    sessionId,
    createdAt,
    language,
  } = payload;

  const body = `
New customer complaint

Phone: ${phone}
Language: ${language}
Location: ${locationId || "unknown"}
When: ${orderDateHint}
Issue: ${issue}

Session ID: ${sessionId}
Timestamp: ${new Date(createdAt).toLocaleString()}

This message was auto-generated by the AI Call Center.
  `;

  await transporter.sendMail({
    from: EMAIL_SMTP_USER,
    to: COMPLAINTS_TO,
    subject: `Customer complaint from ${phone}`,
    text: body,
  });

  console.log("[email] Complaint email sent successfully.");
}

module.exports = { sendComplaintEmail };

