// src/pages/DemoLogs.jsx
//
// Internal "Demo call logs" screen.
// Shows demo-only sessions generated by Call Simulator / debug tools.
// Groups entries by session, allows filtering, and exposes a transcript-like
// timeline for the selected call.

import { useState } from "react";
import { getDemoLogs, clearDemoLogs } from "../data/demoLogs.js";
import { seedLocations } from "../data/seedData.js";

function formatDateTime(iso) {
  if (!iso) return "—";
  try {
    const d = new Date(iso);
    return d.toLocaleString();
  } catch {
    return iso;
  }
}

function findLocationName(locationId) {
  if (!locationId) return "—";
  const loc = seedLocations.find((l) => l.id === locationId);
  return loc ? loc.name : locationId;
}

function groupLogsBySession(logs) {
  const bySession = new Map();

  for (const log of logs) {
    const id = log.sessionId || "unknown";
    if (!bySession.has(id)) {
      bySession.set(id, { sessionId: id, events: [] });
    }
    bySession.get(id).events.push(log);
  }

  const sessions = [];

  for (const value of bySession.values()) {
    const events = [...value.events].sort(
      (a, b) =>
        new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
    );
    const first = events[0];
    const last = events[events.length - 1];

    const anyWithOrder =
      [...events]
        .reverse()
        .find((e) => e.raw?.order || e.orderSummary || e.raw?.orderSummary) ||
      null;

    const locationId =
      last.locationId ||
      first.locationId ||
      anyWithOrder?.raw?.order?.locationId ||
      null;

    const phone =
      last.phone ||
      first.phone ||
      anyWithOrder?.raw?.order?.phone ||
      null;

    const language =
      last.language || first.language || anyWithOrder?.language || null;

    const hasHumanEscalation = events.some(
      (e) => e.hasHumanEscalation || e.type === "human-escalation"
    );

    const complaintId =
      events.find((e) => e.complaintId)?.complaintId || null;

    sessions.push({
      sessionId: value.sessionId,
      startedAt: first.createdAt,
      endedAt: last.createdAt,
      locationId,
      phone,
      language,
      hasHumanEscalation,
      complaintId,
      events,
    });
  }

  // Newest sessions first
  return sessions.sort(
    (a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime()
  );
}

function summarizeOrderFromEvents(events) {
  const withOrder =
    [...events]
      .reverse()
      .find((e) => e.raw?.order || e.orderSummary || e.raw?.orderSummary) ||
    null;

  if (!withOrder) return "No order captured";

  if (withOrder.orderSummary || withOrder.raw?.orderSummary) {
    return withOrder.orderSummary || withOrder.raw.orderSummary;
  }

  const order = withOrder.raw?.order;
  if (
    !order ||
    !Array.isArray(order.items) ||
    order.items.length === 0
  ) {
    return "Order captured (no items listed)";
  }

  const item = order.items[0];
  const size = item.size || "";
  const crust = item.crust || "";
  const toppings = Array.isArray(item.toppings)
    ? item.toppings.length
    : 0;

  const type =
    order.orderType === "delivery"
      ? "Delivery"
      : order.orderType === "pickup"
      ? "Pickup"
      : "Order";

  const parts = [type.trim()];
  if (size) parts.push(size);
  if (crust) parts.push(crust);
  if (toppings) parts.push(`${toppings} toppings`);

  return parts.join(" • ");
}

export default function DemoLogs() {
  const [selectedSessionId, setSelectedSessionId] = useState(null);
  const [locationFilter, setLocationFilter] = useState("all");
  const [timeFilter, setTimeFilter] = useState("24h"); // 24h | 7d | all
  const [now, setNow] = useState(() => Date.now());

  // Re-run when refreshKey changes (we don't memo; this is cheap)
  const logs = getDemoLogs();
  const sessions = groupLogsBySession(logs);

  // Distinct location IDs found in logs
  const locationIds = Array.from(
    new Set(
      sessions
        .map((s) => s.locationId)
        .filter(Boolean)
    )
  );

  const filteredSessions = sessions.filter((s) => {
    if (locationFilter !== "all" && s.locationId !== locationFilter) {
      return false;
    }

    if (timeFilter === "all") return true;

    const startedAtMs = new Date(s.startedAt).getTime();
    if (Number.isNaN(startedAtMs)) return true;

    if (timeFilter === "24h") {
      return now - startedAtMs <= 24 * 60 * 60 * 1000;
    }
    if (timeFilter === "7d") {
      return now - startedAtMs <= 7 * 24 * 60 * 60 * 1000;
    }

    return true;
  });

  const selectedSession =
    filteredSessions.find(
      (s) => s.sessionId === selectedSessionId
    ) || filteredSessions[0] || null;

  function handleRefresh() {
    setNow(Date.now());
  }

  function handleClear() {
    const ok = window.confirm(
      "Clear all demo logs? This only affects demo/test data."
    );
    if (!ok) return;
    clearDemoLogs();
    setSelectedSessionId(null);
    setNow(Date.now());
  }

  function handleSelectSession(id) {
    setSelectedSessionId(id);
  }

  return (
    <div className="space-y-4">
      <header className="space-y-1">
        <h2 className="text-lg font-semibold">Demo call logs</h2>
        <p className="text-sm text-gray-600">
          This view shows{" "}
          <span className="font-medium">demo-only</span> call
          activity generated from the Call Simulator and debug tools.
          In production, this would be backed by the real database +
          telephony logs.
        </p>
      </header>

      {/* Filters + actions */}
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div className="flex flex-wrap items-center gap-2 text-xs md:text-sm">
          <label className="flex items-center gap-1">
            <span className="text-gray-600">Location</span>
            <select
              className="border rounded px-2 py-1 text-xs md:text-sm bg-white"
              value={locationFilter}
              onChange={(e) => setLocationFilter(e.target.value)}
            >
              <option value="all">All locations</option>
              {locationIds.map((id) => (
                <option key={id} value={id}>
                  {findLocationName(id)}
                </option>
              ))}
            </select>
          </label>

          <label className="flex items-center gap-1">
            <span className="text-gray-600">Time</span>
            <select
              className="border rounded px-2 py-1 text-xs md:text-sm bg-white"
              value={timeFilter}
              onChange={(e) => setTimeFilter(e.target.value)}
            >
              <option value="24h">Last 24 hours</option>
              <option value="7d">Last 7 days</option>
              <option value="all">All time</option>
            </select>
          </label>
        </div>

        <div className="flex items-center gap-2 text-xs md:text-sm">
          <button
            type="button"
            onClick={handleRefresh}
            className="px-3 py-1.5 rounded-md border text-gray-700 bg-white hover:bg-gray-50"
          >
            Refresh
          </button>
          <button
            type="button"
            onClick={handleClear}
            className="px-3 py-1.5 rounded-md border border-red-200 text-red-700 bg-red-50 hover:bg-red-100"
          >
            Clear demo logs
          </button>
        </div>
      </div>

      {/* Empty state */}
      {filteredSessions.length === 0 ? (
        <div className="border rounded-md px-4 py-6 text-sm text-gray-600 bg-gray-50">
          <p className="font-medium mb-1">No demo calls logged yet.</p>
          <p>
            Run a few test calls from the{" "}
            <span className="font-semibold">Call Simulator</span> or
            other tools and they&apos;ll appear here.
          </p>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
          {/* Sessions list */}
          <div className="border rounded-lg bg-gray-50/60">
            <div className="border-b px-4 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Sessions ({filteredSessions.length})
            </div>
            <ul className="divide-y text-sm">
              {filteredSessions.map((s) => {
                const isSelected =
                  selectedSession &&
                  selectedSession.sessionId === s.sessionId;
                const orderSummary = summarizeOrderFromEvents(
                  s.events
                );
                const locationName = findLocationName(s.locationId);

                return (
                  <li
                    key={s.sessionId}
                    className={
                      "px-4 py-3 cursor-pointer hover:bg-white/80 " +
                      (isSelected
                        ? "bg-white shadow-inner border-l-4 border-l-rose-600"
                        : "")
                    }
                    onClick={() => handleSelectSession(s.sessionId)}
                  >
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <div className="font-medium text-gray-900 truncate">
                        {locationName}
                      </div>
                      <div className="text-xs text-gray-500">
                        {formatDateTime(s.startedAt)}
                      </div>
                    </div>
                    <div className="text-xs text-gray-600 mb-1">
                      {orderSummary}
                    </div>
                    <div className="flex flex-wrap gap-1 text-[11px]">
                      <span className="px-2 py-0.5 rounded-full bg-white border border-gray-200 text-gray-600">
                        Session: {s.sessionId.slice(0, 8)}…
                      </span>
                      {s.phone && (
                        <span className="px-2 py-0.5 rounded-full bg-white border border-gray-200 text-gray-600">
                          📞 {s.phone}
                        </span>
                      )}
                      {s.language && (
                        <span className="px-2 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700">
                          Lang: {s.language}
                        </span>
                      )}
                      {s.hasHumanEscalation && (
                        <span className="px-2 py-0.5 rounded-full bg-amber-50 border border-amber-200 text-amber-700">
                          ⚠ Human escalation
                        </span>
                      )}
                      {s.complaintId && (
                        <span className="px-2 py-0.5 rounded-full bg-rose-50 border border-rose-200 text-rose-700">
                          Complaint linked
                        </span>
                      )}
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>

          {/* Session detail */}
          <div className="border rounded-lg bg-white">
            {selectedSession ? (
              <div className="flex flex-col h-full">
                <div className="border-b px-4 py-2 space-y-1">
                  <div className="flex items-center justify-between gap-2">
                    <h3 className="text-sm font-semibold text-gray-900">
                      Session details
                    </h3>
                    <span className="text-xs text-gray-500">
                      {formatDateTime(selectedSession.startedAt)} →{" "}
                      {formatDateTime(selectedSession.endedAt)}
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-1 text-[11px]">
                    <span className="px-2 py-0.5 rounded-full bg-gray-50 border border-gray-200 text-gray-700">
                      {findLocationName(selectedSession.locationId)}
                    </span>
                    {selectedSession.phone && (
                      <span className="px-2 py-0.5 rounded-full bg-gray-50 border border-gray-200 text-gray-700">
                        📞 {selectedSession.phone}
                      </span>
                    )}
                    {selectedSession.language && (
                      <span className="px-2 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700">
                        Lang: {selectedSession.language}
                      </span>
                    )}
                    {selectedSession.hasHumanEscalation && (
                      <span className="px-2 py-0.5 rounded-full bg-amber-50 border border-amber-200 text-amber-700">
                        ⚠ Human escalation
                      </span>
                    )}
                    {selectedSession.complaintId && (
                      <span className="px-2 py-0.5 rounded-full bg-rose-50 border border-rose-200 text-rose-700">
                        Complaint linked
                      </span>
                    )}
                  </div>
                </div>

                <div className="flex-1 overflow-auto px-4 py-3 space-y-2 text-sm">
                  {selectedSession.events.map((e) => (
                    <div
                      key={e.id}
                      className="border rounded-md px-3 py-2 bg-gray-50"
                    >
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <div className="text-xs font-medium text-gray-700">
                          {e.type || "event"}
                        </div>
                        <div className="text-[11px] text-gray-500">
                          {formatDateTime(e.createdAt)}
                        </div>
                      </div>

                      {e.transcript && (
                        <p className="text-sm text-gray-800 whitespace-pre-line">
                          {e.transcript}
                        </p>
                      )}

                      {!e.transcript && e.raw?.userInput && (
                        <p className="text-sm text-gray-800">
                          <span className="font-semibold">Caller:</span>{" "}
                          {e.raw.userInput}
                        </p>
                      )}

                      {!e.transcript &&
                        Array.isArray(e.raw?.responses) &&
                        e.raw.responses.length > 0 && (
                          <div className="mt-1 space-y-0.5">
                            {e.raw.responses.map((r, idx) => (
                              <p
                                key={idx}
                                className="text-sm text-gray-700"
                              >
                                <span className="font-semibold">
                                  Agent:
                                </span>{" "}
                                {r.text}
                              </p>
                            ))}
                          </div>
                        )}

                      {e.audioUrl && (
                        <div className="mt-2">
                          <audio
                            controls
                            src={e.audioUrl}
                            className="w-full"
                          />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="h-full flex items-center justify-center text-sm text-gray-500 px-4 py-6">
                Select a session on the left to view the transcript
                and audio timeline.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

